function C = methodPlotStyle( method )
%
% Return a cell of options used with plot for the specified method.
% Use the returned cell C like plot(..., C{:})
%
Mets = {'bahsic','balsmi', 'fohsic','folsmi', 'mrmr', 'pc', 'pghsic', ...
    'pglsmi', 'relief'};
Inds = num2cell(1:length(Mets));

MethodIndexMap = containers.Map(Mets, Inds);

linestyles = cellstr(char('-','-','-','-','-','-','--','-.','--','-',...
    ':','-.','-','--',':','-',':',...
'-.','--','-',':','-.',':','-',':','-.', ...
'-', ':', '--', '-.' , ':', '--' ,'-' ,'-.', '--',':'));


MarkerEdgeColors=['r','b','m','g','c','k',...
'b','m','k','c','g','r','b','m','k','c','g',...
'r','c','b','k','m','g','b','m','y','k','c','g','r'];


Markers=['o','d','p','x','s','x','v','^','<','>','+','h','.',...
'+','*','o','x','^','<','h','.','>','p','s','d','v',...
'o','x','+','*','s','d','v','^','<','>','p','h','.'];

if strcmp(method, 'pglsmi')
    lw = 9;
else
    lw = 5;
end
    
if MethodIndexMap.isKey(method)
    mi = MethodIndexMap(method);
else
    C = {[linestyles{10}, Markers(10)], ...
        'Color', [0.8, 0.5, 1] , ...
        'LineWidth', lw, ...
        'MarkerFaceColor', 'k', ...
        'MarkerEdgeColor', MarkerEdgeColors(end-10), ...
        'MarkerSize', 3};
    return
end

CMap = hsv(9); 

C = {[linestyles{mi}, Markers(mi)], ...
        'Color', CMap(mi,:), ...
        'LineWidth', lw, ...
        'MarkerFaceColor', 'k', ...
        'MarkerEdgeColor', MarkerEdgeColors(end-mi), ...
        'MarkerSize', 3};

end

