function C = methodPlotStyle2( method )
%
% Return a cell of options used with plot for the specified method.
% Specifically design to emphasize l1-LSMI
%

lw = 8;

CM = methodColor( );
if strcmp(method, 'mrmr')
    C = {'--*', ...
        'Color', CM('mrmr'), ...
        'LineWidth', lw-2, ...
        'MarkerSize', 1};
elseif strcmp(method, 'relief')
    C = {':^', ...
        'Color', CM('relief'), ...
        'LineWidth', lw-1, ...
        'MarkerSize', 3};
elseif strcmp(method, 'pc')
    C = {'-s', ...
        'Color', CM('pc'), ...
        'LineWidth', lw-4, ...
        'MarkerSize', 1};
elseif strcmp(method, 'pghsic')
    C = {'-.o', ...
        'Color', CM('pghsic'), ...
        'LineWidth', lw-4, ...
        'MarkerSize', 8, ...
        'MarkerEdgeColor', 'black', ...
        'MarkerFaceColor',[ .49 1 .63]};
elseif strcmp(method, 'pglsmi')
    C = {'-o', ...
        'Color', CM('pglsmi'), ...
        'LineWidth', lw, ...
        'MarkerSize', 1};
elseif strcmp(method, 'fohsic')
    C = {':d', ...
        'Color', CM('fohsic'), ...
        'LineWidth', 11, ...
        'MarkerSize', 2};
elseif strcmp(method, 'folsmi')
    C = {':d', ...
        'Color', CM('folsmi'), ...
        'LineWidth', 11, ...
        'MarkerSize', 2};
elseif strcmp(method, 'bahsic')
    C = {'--p', ...
        'Color', CM('bahsic'), ...
        'LineWidth', 11, ...
        'MarkerSize', 0.7};
elseif strcmp(method, 'balsmi')
    C = {'--<', ...
        'Color', CM('balsmi'), ...
        'LineWidth', 11, ...
        'MarkerSize', 0.7};

elseif strcmp(method, 'qpfs')
    C = {'--^', ...
        'Color', CM('qpfs'), ...
        'LineWidth', lw - 3, ...
        'MarkerSize', 9};

elseif strcmp(method, 'lasso')
    C = {'-p', ...
        'Color', CM('lasso'), ...
        'LineWidth', lw - 4, ...
        'MarkerSize', 12};

else
    C = {':ok'};
    
end


end

